name: 'Issues to Totangoo'
description: 'Creates a Totango touchpoint when an issue is opened'
inputs:
  ACCOUNT_ID:
    description: 'Customer account id'
    required: true
  APP_TOKEN:
    description: 'Totango API Token Key'
    required: true
  ACTIVITY_TYPE:
    description: 'Type from the `Success Flow` section'
    required: true
  TOUCHPOINT_TYPE:
    description: 'The id value of the touchpoint type.'
    required: true
  TOUCHPOINT_TAGS:
    description: 'The id value of the touchpoint reason.'
    required: true
outputs:
  touchpoint_id:
    description: 'The id of the newly created touchpoint'
runs:
  using: 'node12'
  main: 'index.js'